export const staticProducts = [
  {
    id: "1",
    name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    category: "electronics",
    image: "https://m.media-amazon.com/images/I/51aXvjzcukL._SX679_.jpg",
    brand: "Sony",
    price: 348.0,
    features: [
      { name: "Category", value: "electronics" },
      { name: "Rating", value: "4.7 (8,500 reviews)" },
      { name: "Battery Life", value: "30 hours" },
      { name: "Connectivity", value: "Bluetooth 5.2" },
    ],
    description:
      "Premium wireless headphones with exceptional noise cancellation and up to 30 hours of battery life.",
    stock: "In Stock",
    warranty: "1 Year Sony India Warranty",
    dimensions: "7.3 x 3 x 10.3 inches",
    shipping: "Free 2-day Delivery",
  },
  {
    id: "2",
    name: "Logitech MX Master 3S Wireless Performance Mouse",
    category: "electronics",
    image:
      "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Computer%20Accessories%20and%20Tablets%20Accessories/Images/258454_0_rmm57f.png?tr=w-1000",
    price: 99.99,
    brand: "Logitech",
    features: [
      { name: "Category", value: "electronics" },
      { name: "Rating", value: "4.8 (12,000 reviews)" },
      { name: "Battery Life", value: "70 days" },
      { name: "Connectivity", value: "Bluetooth / USB Receiver" },
    ],
    description:
      "Ergonomic wireless mouse with quiet clicks, ultra-fast scrolling, and app-specific customizations.",
    stock: "Only 5 left in stock",
    warranty: "2 Years Logitech Warranty",
    dimensions: "4.9 x 3.3 x 2 inches",
    shipping: "Free Shipping on Orders Above ₹500",
  },
  {
    id: "3",
    name: "Apple 2024 MacBook Air Laptop M3 chip",
    category: "electronics",
    image: "https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg",
    price: 1199.0,
    brand: "Apple",
    features: [
      { name: "Category", value: "electronics" },
      { name: "Rating", value: "4.9 (2,300 reviews)" },
      { name: "Battery Life", value: "18 hours" },
      { name: "Storage", value: "512GB SSD" },
    ],
    description:
      "Ultra-thin MacBook Air powered by the M3 chip for blazing-fast performance and incredible battery life.",
    stock: "In Stock",
    warranty: "1 Year Apple Limited Warranty",
    dimensions: "11.97 x 8.46 x 0.44 inches",
    shipping: "Free Express Delivery",
  },
  {
    id: "4",
    name: "Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB, 256GB)",
    category: "mobile",
    image: "https://m.media-amazon.com/images/I/81njZjDqc6L._SX679_.jpg",
    price: 1299.99,
    brand: "Samsung",
    features: [
      { name: "Category", value: "mobile" },
      { name: "Rating", value: "4.6 (3,400 reviews)" },
      { name: "Battery Life", value: "26 hours" },
      { name: "Storage", value: "256GB" },
    ],
    description:
      "Flagship smartphone with powerful camera, 5G performance, and elegant titanium body.",
    stock: "Limited Stock",
    warranty: "1 Year Manufacturer Warranty",
    dimensions: "6.4 x 3 x 0.35 inches",
    shipping: "Free Delivery within 3 Days",
  },
  {
    id: "5",
    name: "iPhone 15 Pro Max (256 GB) - Natural Titanium",
    category: "mobile",
    image: "https://m.media-amazon.com/images/I/81CgtwSII3L._AC_SL1500_.jpg",
    price: 1399.99,
    brand: "Apple",
    features: [
      { name: "Category", value: "mobile" },
      { name: "Rating", value: "4.9 (5,200 reviews)" },
      { name: "Battery Life", value: "29 hours" },
      { name: "Storage", value: "256GB" },
    ],
    description:
      "Apple's most advanced iPhone featuring A17 Pro chip, titanium frame, and stunning ProMotion display.",
    stock: "In Stock",
    warranty: "1 Year Apple India Warranty",
    dimensions: "6.29 x 3.02 x 0.32 inches",
    shipping: "Free Same-Day Delivery (Metro Cities)",
  },
  {
    id: "6",
    name: "OnePlus 12R 5G (Iron Gray, 16GB RAM, 256GB Storage)",
    category: "mobile",
    image:
      "https://prodondcdoc.easypay.co.in/ondc_seller_product/EP_SELLER_ZH8ITDDUGD/EP_SELLER_ZH8ITDDUGD_IMG_1739099971243.png",
    price: 49999.0,
    brand: "OnePlus",
    features: [
      { name: "Category", value: "mobile" },
      { name: "Rating", value: "4.5 (1,800 reviews)" },
      { name: "Battery Life", value: "32 hours" },
      { name: "Storage", value: "256GB" },
    ],
    description:
      "High-performance smartphone with Snapdragon 8 Gen 2 and super-fast 100W charging.",
    stock: "Available",
    warranty: "1 Year OnePlus Warranty",
    dimensions: "6.5 x 2.9 x 0.34 inches",
    shipping: "Free Delivery in 2-4 Days",
  },
  {
    id: "7",
    name: "JBL Flip 6 Portable Bluetooth Speaker",
    category: "electronics",
    image: "https://m.media-amazon.com/images/I/41QBa9gm++L._SY300_SX300_.jpg",
    brand: "JBL",
    price: 129.95,
    features: [
      { name: "Category", value: "electronics" },
      { name: "Rating", value: "4.7 (15,000 reviews)" },
      { name: "Battery Life", value: "12 hours" },
      { name: "Connectivity", value: "Bluetooth 5.1" },
    ],
    description:
      "Rugged, waterproof speaker with deep bass and 12 hours of playtime — perfect for outdoor use.",
    stock: "In Stock",
    warranty: "1 Year JBL Warranty",
    dimensions: "7 x 2.6 x 2.8 inches",
    shipping: "Free Shipping (Standard)",
  },
  {
    id: "8",
    name: "Google Pixel 8 Pro (128GB, Obsidian Black)",
    category: "mobile",
    image: "https://m.media-amazon.com/images/I/61+Q6Rh3OQL._AC_SL1500_.jpg",
    brand: "Google",
    price: 999.0,
    features: [
      { name: "Category", value: "mobile" },
      { name: "Rating", value: "4.6 (2,800 reviews)" },
      { name: "Battery Life", value: "24 hours" },
      { name: "Storage", value: "128GB" },
    ],
    description:
      "AI-powered smartphone with the latest Google Tensor G3 chip and exceptional camera performance.",
    stock: "Few Units Left",
    warranty: "1 Year Google India Warranty",
    dimensions: "6.4 x 3 x 0.35 inches",
    shipping: "Free Next-Day Delivery",
  },
  {
    id: "9",
    name: "boAt Stone 1200 14W Bluetooth Speaker",
    category: "electronics",
    image: "https://m.media-amazon.com/images/I/61uA2UVnYWL._SX679_.jpg",
    brand: "boAt",
    price: 64.99,
    features: [
      { name: "Category", value: "electronics" },
      { name: "Rating", value: "4.5 (20,000 reviews)" },
      { name: "Battery Life", value: "9 hours" },
      { name: "Connectivity", value: "Bluetooth 5.0 / AUX" },
    ],
    description:
      "Compact and powerful speaker with deep bass, RGB lights, and IPX7 waterproof rating.",
    stock: "In Stock",
    warranty: "1 Year boAt Warranty",
    dimensions: "9 x 3.3 x 4.2 inches",
    shipping: "Free Delivery within 5 Days",
  },
  {
    id: "10",
    name: "HP Z3700 Wireless Optical Mouse",
    category: "electronics",
    image: "https://m.media-amazon.com/images/I/614DbY9tQsL._SX679_.jpg",
    price: 25.0,
    brand: "HP",
    features: [
      { name: "Category", value: "electronics" },
      { name: "Rating", value: "4.4 (6,800 reviews)" },
      { name: "Battery Life", value: "16 months (AA battery)" },
      { name: "Connectivity", value: "2.4GHz Wireless" },
    ],
    description:
      "Ultra-slim wireless mouse with precise optical tracking and long battery life.",
    stock: "In Stock",
    warranty: "1 Year HP Warranty",
    dimensions: "3.95 x 2.3 x 1 inches",
    shipping: "Free Delivery in 3-5 Business Days",
  },
  {
    id: "11",
    name: "Dell Inspiron 14 Laptop (i5 13th Gen, 16GB, 512GB SSD)",
    category: "electronics",
    image: "https://m.media-amazon.com/images/I/814WFVz-BCL._SX679_.jpg",
    brand: "Dell",
    price: 849.99,
    features: [
      { name: "Category", value: "electronics" },
      { name: "Rating", value: "4.2 (3,100 reviews)" },
      { name: "Battery Life", value: "10 hours" },
      { name: "Storage", value: "512GB SSD" },
    ],
    description:
      "Reliable and sleek laptop with 13th Gen Intel Core performance and fast SSD storage.",
    stock: "In Stock",
    warranty: "1 Year Dell Onsite Warranty",
    dimensions: "12.7 x 8.5 x 0.7 inches",
    shipping: "Free Delivery",
  },
  {
    id: "12",
    name: "Sennheiser HD 450BT Wireless Over Ear Headphones",
    category: "electronics",
    image: "https://m.media-amazon.com/images/I/71sLOtsK2UL._SL1500_.jpg",
    brand: "Sennheiser",
    price: 149.95,
    features: [
      { name: "Category", value: "electronics" },
      { name: "Rating", value: "4.6 (4,200 reviews)" },
      { name: "Battery Life", value: "30 hours" },
      { name: "Connectivity", value: "Bluetooth 5.0 / AptX" },
    ],
    description:
      "Dynamic and comfortable over-ear headphones with active noise cancellation and 30-hour battery.",
    stock: "In Stock",
    warranty: "2 Years Sennheiser Warranty",
    dimensions: "6.1 x 3.1 x 8.7 inches",
    shipping: "Free Standard Shipping",
  },
];
